### ISSUE TITLE
Nomad Helper for Super.Human.Portal

### ISSUE THREAD

**Issue by JoelProminic** [STARTcloud/hcl_roles#6]
In [this issue](https://github.com/Moonshine-IDE/Super.Human.Portal/issues/53), we have been working on a better way for Super.Human.Portal to open the Nomad links.  We have a working solution for this, so we'd like to get it added to the provisioners.

The components are:

### Updates to [haproxy.cfg](https://github.com/STARTcloud/startcloud_roles/blob/main/startcloud_haproxy/templates/haproxy.cfg.j2)

Comment out these lines or update the configuration so that they don't apply to Nomad:

```
    ##BEGIN CORS
    #http-response set-header Access-Control-Allow-Origin "*"
    #http-response set-header Access-Control-Allow-Headers "Origin, X-Requested-With, Content-Type, Accept, Authorization, JSNLog-RequestId, activityId, applicationId, applicationUserId, channelId, senderId, sessionId"
    #http-response set-header Access-Control-Max-Age 3628800
    #http-response set-header Access-Control-Allow-Methods "*"
    ## END CORS
```

The following three updates are required to add an OPTIONS response for the nomad server.  NOTE: thsi could be done in a more restrictive sway (i.e. limiting it to `nomadweb.*` or returning an explicit origin.

Add a new acl entry after `acl host_downloads`:

```
                acl is_options                method             OPTIONS
```

Add a new use_backend line **before** `restapi`.  The ordering is important for this case.

```
                use_backend                     cors_backend         if is_options
```

Finally, add the new backend at the end of the file, after the `backend nomadweb` section.  Not that this case is expected to return the status code:

```
# CORS preflight requests
backend cors_backend
        http-after-response set-header Access-Control-Allow-Origin "*"
        http-after-response set-header Access-Control-Allow-Headers "*"
        http-after-response set-header Access-Control-Allow-Credentials "true"
        http-after-response set-header Access-Control-Allow-Methods "GET, DELETE, OPTIONS, POST, PUT, PATCH"
        http-after-response set-header Access-Control-Max-Age "31536000"
        http-request return status 200
```

### Updates to [nomad-config.yml](TODO)

Note that the server name needs to be updated for `Access-Control-Allow-Origin`

```
httpHeaders:
  Access-Control-Allow-Origin: https://domino.nomad-1010.nomadtest.com
  Access-Control-Allow-Headers: '*'
  Access-Control-Max-Age: 3600
  Access-Control-Allow-Credentials: true
  Access-Control-Allow-Methods: 'GET, DELETE, OPTIONS, POST, PUT, PATCH'
  Content-Security-Policy: frame-ancestors https://domino.nomad-1010.nomadtest.com;
```

I think we can remove this from my original writeup - I think it was only needed for shared libraries:

```
  Cross-Origin-Resource-Policy: cross-origin     
```

### New File:  nomadhelper.html

We need a new file at `/opt/hcl/domino/notes/latest/linux/nomad-files/nomadhelper.html`.  We can create a template based on [this file](https://github.com/Moonshine-IDE/Super.Human.Portal/blob/features/issue_53_nomad_links/Super.Human.Portal_Royale/src/resources/nomadhelper.html) - I don't see anything that needs to be moved to insertion parameters.

This is associated with Super.Human.Portal rather than Nomad.  We don't have a Super.Human.Portal rol yet, so we may want to create one.  It is currently [part of hcl_domino_genesis_applications](https://github.com/STARTcloud/hcl_roles/blob/612f9c58bf556d25c8128764fc00c2e59d3620ec/hcl_domino_genesis_applications/defaults/main.yml#L5).

The permissions should match the rest of the `nomad-files` directory (owner: `root`, permissions `755`)

## Database Updates for Super.Human.Portal

After we install Super.Human.Portal, we'll want to update a document with a reference to `nomadhelper.html`.   This will be imported into Domino using Genesis.

TODO:  I'll create a template for the JSON file.  This should probably be part of the new Super.Human.Portal role mentioned above.

UPDATE:  I made an update to SuperHumanPortal.nsf to add support for a new configuration parameter, `nomad_helper_url`.

Once we have a provisioner to make the updates for this issue, we can use a JSON file like [this](https://github.com/Moonshine-IDE/Super.Human.Portal/blob/features/issue_53_nomad_links/Super.Human.Portal_Agents/data/create_nomad_helper_url.json) to update the configuration value.  Currently this script assumes the document doesn't exist, but I'd like to make a more robust version.  Here is an [existing example of Genesis JSON](https://github.com/STARTcloud/hcl_roles/blob/612f9c58bf556d25c8128764fc00c2e59d3620ec/hcl_domino_leap/tasks/main.yml#L90-L115).

**Comment by MarkProminic** [comment]
Well, I didn't realize that me pushing fix: https://github.com/STARTcloud/hcl_roles/issues/6 in the commit name would close this.

Leaving it open for confirmations

**Comment by MarkProminic** [comment]
Most of the changes were in the startcloud.startcloud_roles.haproxy role and hcl.hcl_roles.domino_nomadweb.
